### PR TITLE
issue #67 :: added http-header Last-Modified

### LINKED ISSUE #67: p2 need Http-Header Last-Modified
I have deployed a p2 repository (built with tycho) to package drone and want to consume this p2 repository to install the plug-Ins using org.eclipse.equinox.p2.director.

The p2 director log an error message:

!MESSAGE Server returned lastModified <= 0

It seems like the p2 director need a valid Last-Modified Header. Tested with eclipse indigo and luna.

### PR DESCRIPTION
**Pull request by cornzy**
Tried to fix #67.

Additionally uses try-with-resource for the ZipInputStream and refactor the early return (mainly because this way you avoid the eclipse warning bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=371614

### CODE REVIEW

**Comment by ctron** [comment]
Hey thanks! That looks perfect!

The try-with-resource actually is not required, since the stream will be closed by the outer code. But it does not hurt either I guess. And it fixes the warning :wink: 

I will merge it early next week!

Thanks again!

**Comment by cornzy** [comment]
Sorry that was not that perfekt as it looks like. My little test setup yesterday was too ... "little" ;)

First: I the response is not committed after entry was found and set (line 554) hence always an error is reportet which leads to an exception. :(

And although the Last-Modified header is set correct the message from p2-director remains :(

**Comment by cornzy** [comment]
Ok, that was a quite bad performance - sorry for that. Next mistake was: I'd use setHeader instead of setDateHeader... fixed that and tested - no message from p2 director anymore.

Maybe we should directly add the Last-Modified header in other download responses? How many points need to be fixed? Or should we introduce a ResponseUtil to create the necessary header information for an download response?

**Comment by ctron** [comment]
No problem :wink: 

Yes I think this should be added at a central point. There is the [DownloadHelper](https://github.com/ctron/package-drone/blob/5641b6da095b7d7e878ac6f64f5cccc261b948b2/de.dentrassi.pm.storage.service/src/de/dentrassi/pm/storage/service/util/DownloadHelper.java) class which should be the central point to stream artifacts to the HttpServletResponse.

However the UnzipPlugin does not use this, since I only streams an entry of the artifact and not the full artifact.

So if you like you could refactor the `DownloadHelper` class to provide a more generic method, which would match the `UnzipServlet` and the other methods in `DownloadHelper` at the same time. Though I did not check it, I think it should be possible.

**Pull request merged**
